language: node_js
sudo: required
dist: trusty
node_js:
- '5'
before_install:
- npm install bower
- ./node_modules/bower/bin/bower install
before_script:
- sudo add-apt-repository ppa:dhor/myway -y
- sudo apt-get update -qq
- sudo apt-get install graphicsmagick -y
- gm version
after_success:
- ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info
env:
  global:
    - secure: YWABlINoIkwl9RFLOW9G0lATEP3aiXXi+DS6TWfvQWWG/jkS5sn7IqWC2U67LjwQ0lDg0yevo3ZD7FyYQ5lr8AVuScAZ6P2o2dm9t/HBKGTG4u016dxbWWYVZ8MAlKT7TfjVD8iDzcWyZedsbpuyaNNp4pGr/CNcvq7TGdJLNkU=
    - CI=1
    - TOLERANCE=0.002
    - DELAY=5000
